### PR TITLE
Fix OpenLoopCoronary equations

### LINKED ISSUE #107: Open loop coronary block missing terms
### Description

While trying to add some test cases that compare simulation results with analytical solutions (#99), @AndreaZanoni figured out that the open loop coronary blocks might be missing some terms relating to the initial condition.

### Reproduction

We will add in more details to reproduce the error shortly. Requires a little bit of investigation. 

### Expected behavior

We are expecting a simulation using the closed loop coronary to match an analytical solution throughout the simulation. Currently it only matches later in the simulation, not close to the initial condition.

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

### PR DESCRIPTION
**Pull request by menon-karthik**
## Current situation
Closes #107 

The equations for the open loop coronary block were missing a few terms relating to the initial condition. While fixing this, I also noticed that the equation for the steady state initial condition was wrong. 

## Release Notes 
* Added new functions `Block::setup_initial_state_dependent_params` and `Model::setup_initial_state_dependent_parameters` to set up block-specific parameters that depend on the initial state vector
* Added new terms to the OpenLoopCoronary equations to account for the initial condition.
* Fixed the steady state equations for OpenLoopCoronaryBC
* Miscellaneous: Minor edits to the WindkesselBC documentation
* Miscellaneous: Allow a user to run the solver without specifying the name of the output. Default output file will be written with name `output.csv`. This is already a feature when running using the Python API. Just added it to the CMake build executable. 

## Documentation
 
* Updated docs to add new equations for OpenLoopCoronaryBC

## Testing
Tests passing. 

## Code of Conduct & Contributing Guidelines 
- [x] I agree to follow the [Code of Conduct](https://github.com/SimVascular/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/SimVascular/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

File: src/model/OpenLoopCoronaryBC.h [hunk 1]
```diff
@@ -58,16 +59,18 @@
...
+ * C_{i m} R_{v} \frac{d P_{a}}{d t}=0
+ * \f}
  *
- * \f[
- * C_{i m} R_v P^{e}-C_{i m} R_{v} R_{a} Q^{e}-R_{v} V_{i m}^{e}-C_{i m} R_{v}
- * P_{i m}-C_{i m} R_{v} R_{a m} \frac{d V_{i m}^{e}}{d t}-R_{a m} V_{i
- * m}^{e}-C_{i m} R_{a m} P_{i m}+R_{a m} C_{i m} P_{v}=0 \f]
+ * \f{eqnarray*}{
+ * &C_{i m} R_v P_{in}-C_{i m} R_{v} R_{a} Q_{in}-R_{v} V_{i m}-C_{i
+ * m}\left(R_{v}+R_{a m}\right) \left(P_{c i m}(0)-P_{i m}(0)+P_{i
```
Comment (JonathanPham) [inline src/model/OpenLoopCoronaryBC.h:71]: Should the "\left(P_{c i m}(0)-P_{i m}(0)" term in line 71 be "\left(-P_{c i m}(0)+P_{i m}(0)" (basically, switched signs)? Does that agree with your math, @menon-karthik?

File: src/model/OpenLoopCoronaryBC.h [hunk 2]
```diff
@@ -85,9 +88,10 @@
  * & -C_{i m} R_{v} R_{a} & -\left(R_{v}+R_{a m}\right)\end{array}\right] \f]
  *
  * \f[
- * \mathbf{c}^{e}=\left[\begin{array}{c}C_{i m}\left(-P_{i m}+P_{v}\right)+C_{a}
- * C_{i m} R_{v} \frac{d P_{a}}{d t} \\-C_{i m}\left(R_{v}+R_{a m}\right) P_{i
- * m}+R_{a m} C_{i m} P_{v}\end{array}\right] \f]
+ * \mathbf{c}^{e}=\left[\begin{array}{c}C_{i m}\left(-P_{i m}+P_{i m}(0)-P_{c i
+ * m}(0)+P_{v}\right)+C_{a} C_{i m} R_{v} \frac{d P_{a}}{d t} \\-C_{i
+ * m}\left(R_{v} + R_{a m}\right)\left(P_{cim}(0)-P_{i m}(0)+P_{i m}\right)+R_{a
```
Comment (JonathanPham) [inline src/model/OpenLoopCoronaryBC.h:93]: Should the "\left(P_{cim}(0)-P_{i m}(0)" term in line 93 be "\left(-P_{cim}(0)+P_{i m}(0)" (basically, switched signs)?

File: src/model/OpenLoopCoronaryBC.h [hunk 3]
```diff
@@ -58,16 +59,18 @@
  *
  * ### Governing equations
  *
- * \f[
- * C_{i m} R_{v} Q_{in}-V_{i m}-C_{i m} P_{i m}+C_{i m} P_{v}-C_{i m} R_{v}
- * \frac{d V_{i m}}{d t}-C_{a} C_{i m} R_{v} \frac{d P_{in}}{d t}+R_{a} C_{a}
- * C_{i m} R_{v} \frac{d Q_{in}}{d t}+C_{a} C_{i m} R_{v} \frac{d P_{a}}{d
- * t}=0 \f]
+ * \f{eqnarray*}{
+ * &C_{i m} R_{v} Q_{in}-V_{i m}+C_{i m} \left(-P_{c i m}(0)+P_{i m}(0)-P_{i
```
Comment (JonathanPham) [inline src/model/OpenLoopCoronaryBC.h:63]: Should the "\left(-P_{c i m}(0)+P_{i m}(0)" term in line 63 be "\left(P_{c i m}(0)-P_{i m}(0)" instead? Basically, switched signs?

File: src/model/OpenLoopCoronaryBC.h [hunk 4]
```diff
@@ -85,9 +88,10 @@
  * & -C_{i m} R_{v} R_{a} & -\left(R_{v}+R_{a m}\right)\end{array}\right] \f]
  *
  * \f[
- * \mathbf{c}^{e}=\left[\begin{array}{c}C_{i m}\left(-P_{i m}+P_{v}\right)+C_{a}
- * C_{i m} R_{v} \frac{d P_{a}}{d t} \\-C_{i m}\left(R_{v}+R_{a m}\right) P_{i
- * m}+R_{a m} C_{i m} P_{v}\end{array}\right] \f]
+ * \mathbf{c}^{e}=\left[\begin{array}{c}C_{i m}\left(-P_{i m}+P_{i m}(0)-P_{c i
```
Comment (JonathanPham) [inline src/model/OpenLoopCoronaryBC.h:91]: Should the "+P_{i m}(0)-P_{c i" term in line 91 be "-P_{i m}(0)+P_{c i" instead (basically, switched signs)?

File: src/model/OpenLoopCoronaryBC.cpp [hunk 5]
```diff
@@ -74,10 +74,32 @@ void OpenLoopCoronaryBC::update_time(SparseSystem &system,
   auto Pv = parameters[global_param_ids[6]];
 
   if (steady) {
-    system.C(global_eqn_ids[0]) = -Cim * Pim;
     system.C(global_eqn_ids[1]) = Pv;
   } else {
-    system.C(global_eqn_ids[0]) = Cim * (-Pim + Pv);
-    system.C(global_eqn_ids[1]) = -Cim * (Rv + Ram) * Pim + Ram * Cim * Pv;
+    system.C(global_eqn_ids[0]) =
+        Cim * (-Pim + Pv + this->Pim_0 - this->P_Cim_0);
```
Comment (JonathanPham) [inline src/model/OpenLoopCoronaryBC.cpp:80]: Should "this->Pim_0 - this->P_Cim_0" in line 80 be "-this->Pim_0 + this->P_Cim_0" (basically, switched signs)? Because I think all the "Vim" terms in the original equation should be replaced with "Vim - Cim * (P_Cim_0 - Pim_0)". Does that agree with your math, @menon-karthik?

File: src/model/OpenLoopCoronaryBC.cpp [hunk 6]
```diff
@@ -74,10 +74,32 @@ void OpenLoopCoronaryBC::update_time(SparseSystem &system,
...
+    system.C(global_eqn_ids[1]) =
+        (Ram * Cim * Pv) -
+        Cim * (Rv + Ram) * (Pim + this->P_Cim_0 - this->Pim_0);
```
Comment (JonathanPham) [inline src/model/OpenLoopCoronaryBC.cpp:83]: Should "this->P_Cim_0 - this->Pim_0" in line 83 be "-this->P_Cim_0 + this->Pim_0" (basically, switched signs)?

**Review by JonathanPham — CHANGES_REQUESTED** [review]
See comments.

**Comment by menon-karthik** [comment]
@JonathanPham responding to all the above comments simultaneously below:

I think the current math is correct. @AndreaZanoni and I verified the expression and also compared the numerical solution with an analytical solution (which it matches with). We plan to add the analytical solution to the tests in a following PR (see #99).

The main fix was to replace `Pim` with `Pim + this->P_Cim_0 - this->Pim_0`

**Review by JonathanPham — APPROVED** [review]
Okay, sounds good.
